# Site settings
name: 安韬
location: 北京海淀
company: 六方云科技有限公司
position: 算法工程师
github: https://github.com/
phone: 1367428XXXX
email: 410828726@qq.com

baseurl: "https://antelx.github.io/"
# baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

