# Site settings
name: 安韬
location: 北京-海淀
company: 北京六方云科技有限公司
position: Java开发工程师
#github: https://github.com/
phone: 1367428XXXX
email: 410828726@qq.com

baseurl: "antelx.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

